name: Post Release Tasks

on:
  workflow_dispatch:
    inputs:
      github_ref_name:
        description: "Current release version (e.g., v1.15.3)"
        required: true
      previous_ref_name:
        description: "Previous release version (e.g., v1.14.8)"
        required: false

jobs:
  post_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # or whatever version you need
          distribution: 'temurin'  # or another distribution

      - name: Run Post Release Tasks
        uses: marcingrzejszczak/micrometer-release@main
        with:
          gh_token: ${{ secrets.TOKEN }}
          github_ref_name: ${{ github.event.inputs.github_ref_name }}
          previous_ref_name: ${{ github.event.inputs.previous_ref_name }}
          spring_release_gchat_webhook_url: ""
          bluesky_handle: ""
          bluesky_password: ""
