name: Manage Milestones

on:
  workflow_dispatch:  # Manual trigger

jobs:
  manage-milestones:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Set milestone for issue #1
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.TOKEN }}
          script: |
            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: 1,
              milestone: 1
            });

      - name: Set milestone for issues #5, #4, and #2
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.TOKEN }}
          script: |
            const issues = [5, 4, 2];
            for (const issueNumber of issues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                milestone: 2
              });
            }

      - name: Delete milestone with title "0.0.3"
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.TOKEN }}
          script: |
            // First, find the milestone by title
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all'
            });
            
            const milestone = milestones.data.find(m => m.title === '0.0.3');
            if (milestone) {
              await github.rest.issues.deleteMilestone({
                owner: context.repo.owner,
                repo: context.repo.repo,
                milestone_number: milestone.number
              });
              console.log('Successfully deleted milestone "0.0.3"');
            } else {
              console.log('No milestone with title "0.0.3" found');
            }

      - name: Delete release "0.0.3"
        uses: actions/github-script@v7
        with:
          github-token: ${{ env.TOKEN }}
          script: |
            try {
              const releases = await github.rest.repos.listReleases({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              
              const release = releases.data.find(r => r.tag_name === 'v0.0.3' || r.name === '0.0.3');
              if (release) {
                await github.rest.repos.deleteRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  release_id: release.id
                });
                console.log('Successfully deleted release "0.0.3"');
              } else {
                console.log('No release with name/tag "0.0.3" found');
              }
            } catch (error) {
              console.log('Error deleting release:', error);
            }
